### ISSUE TITLE
LSDJ can't create save/causes gnuboy to exit on resume

### ISSUE THREAD

**Issue by ishotjr** [PocketSprite/8bkc-gnuboy#4] opened 2018-04-30 03:36 UTC
On first load, LSDJ fails to run, complaining of an inability to create a save file; on subsequent launches, the device returns immediately to the Chooser (removing the state file returns to the initial save file failure).  I'm not too worried about not being able to run LSDJ on my PocketSprite, but I wonder if other carts might be affected?  The same LSDJ version (`5.8.4`) runs fine on [bgb](http://bgb.bircd.org).  Let me know if there are any log files I can share or if trying other versions of LSDJ might be helpful (looks like `6.1.6` is out, I just happened to have `5.8.4` handy).  Thanks! :bowtie:

**Comment by Spritetm** [comment] 2018-04-30 03:40
There's a bug in the stock version of Gnuboy that causes it to crap out on cartridges with large SRAM sizes. Can you try installing http://meuk.spritesserver.nl/tmp/gnuboy-bb17eb115.zip and seeing if that gives a better result?

**Comment by ishotjr** [comment] 2018-04-30 03:55
Ah! I'd just started searching for known gnuboy SRAM issues - will gladly test and advise! ❤️

**Comment by Spritetm** [comment] 2018-05-18 06:38
Did you manage to test the new software to see if the issue is still there?

**Comment by Spritetm** [comment] 2018-06-06 03:52
Closing, I assume the new version fixed things. If not, feel free to re-open.

**Closed as completed by Spritetm** 2018-06-06 03:52 UTC

**Comment by ishotjr** [comment] 2018-06-08 02:09
@Spritetm I replaced the stock `gnuboy.app` with the one from `gnuboy-bb17eb115.zip` and after deleting `lsdj.state` it's now working - thanks! :bowtie: 🚀
